# Generated by Django 3.2.12 on 2022-08-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-created_at']},
        ),
    ]
