# Generated by Django 3.2.12 on 2022-08-04 21:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
