# Generated by Django 3.2.12 on 2022-08-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_projeto_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='views',
        ),
    ]
