# Generated by Django 4.0.6 on 2022-08-06 15:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_remove_projeto_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
