# Generated by Django 3.2.12 on 2022-08-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_alter_professor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='contato',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
