# Generated by Django 4.0.6 on 2022-08-06 15:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('slug', models.SlugField(unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Procure as imagens', null=True, upload_to='media/')),
                ('pesquisa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pesquisas.pesquisa')),
            ],
        ),
    ]
